import Head from "next/head";
import CatagoriesPage from "../components/CatagoriesPage";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Virgin Fashion</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Hero />
      <CatagoriesPage />
    </>
  );
}
